### ISSUE TITLE
404 error when trying to use AI Content Describer

### ISSUE THREAD

**Issue by andrew-l-d** [cartertemm/AI-content-describer#12]
I have just installed AI Content Describer on NVDA 2023.3.1.  I followed all instructions as best as I could.  I already had a Chat GPT account.  Created a secret key and pasted into AI Content Describer.  Added $5 to the account but concerned that money has not been deducted and cannot now find where to add or even check that I did everything correctly.
The error I get is:
Error: http404 not found. The model `gpt-for-vision-preview` noes not exist or you do not have access to it.  Learn more: https://learn.open ai.com/en/articles/7102672-how-can-i-access-gpt-4
The article told me nothing I could understand.
A perplexed Andrew

**Comment by andrew-l-d** [comment]
I have just updated to the latest version of AI Describer and am still getting the 404 error.  That is disappointing, as is the lack of response to the problem.

Andrew

**Comment by cartertemm** [comment]
@andrew-l-d

I must've missed the emails when this issue was created. Sorry to hear you've been running into this. I don't control OpenAI's API directly so if you are getting a 404 it isn't a problem with the addon, but I will do my best to try and help. A couple questions:

* Do you remember which URL you used to create and fund your account? In your issue you talk about ChatGPT, but this addon works with the OpenAI platform and its associated API.
* Since the money was not deducted and you were not charged, go ahead and try to follow the steps in the readme once again. It should give you access after about five minutes of funding the account and obtaining a key for the API.

**Comment by andrew-l-d** [comment]
Thanks Carter.  It was my bad - sort of.  On their rather unfriendly page I missed the Confirm button when entering credit card details.  I am already getting huge pleasure from descriptions of photos.
Andrew

**Comment by andrew-l-d** [comment]
Carter, this is a wonderful resource.  Love the updates.

 

Andrew
